### ISSUE TITLE
Allow multiple Channel IDs

### ISSUE THREAD

**Issue by bobbyl140** [bobbyl140/quote-leaderboard-bot#4]
Easy way: List containing Channel IDs, update `setup.py` to have "Enter Channel IDs separated by `(\ |,|,\ )`".

Hard way: Slash Command with store of Channel IDs (JSON? YML? XML? Plain text because I'm lazy?) and remove the Channel ID importer from `setup.py`.

Self-assigning but accepting contributions (@wacksientrist if you wanna take a stab at it), otherwise will work on it soon™.

**Comment by wacksientrist** [comment]
I made a pr to fix it

**Comment by bobbyl140** [comment]
#9
